version: "3.9"
services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile
    image: webapp:7.0
    ports:
      - "80:5000"
    restart: always
    networks:
      - webnet
networks:
  webnet:
  